from flask import (
    Flask,
    request,
    jsonify,
    render_template,
    redirect,
    session,
    send_file
)

from flask_cors import CORS

from faster_whisper import WhisperModel

from openai import OpenAI

from pydub import AudioSegment

from pydub.silence import split_on_silence

from waitress import serve

from dotenv import load_dotenv

import psycopg2

import threading
import uuid
import os
import re

from datetime import datetime

from openpyxl import Workbook

# =========================================
# ENV
# =========================================

load_dotenv()

OPENAI_API_KEY = os.getenv(
    "OPENAI_API_KEY"
)

DATABASE_URL = os.getenv(
    "DATABASE_URL"
)

ADMIN_USUARIO = os.getenv(
    "ADMIN_USUARIO",
    "admin"
)

ADMIN_SENHA = os.getenv(
    "ADMIN_SENHA",
    "123456"
)

UPLOAD_FOLDER = "uploads"

os.makedirs(
    UPLOAD_FOLDER,
    exist_ok=True
)

# =========================================
# FLASK
# =========================================

app = Flask(__name__)

app.secret_key = os.getenv(
    "SECRET_KEY",
    "55pbx_ai"
)

CORS(app)

# =========================================
# OPENAI
# =========================================

client = OpenAI(
    api_key=OPENAI_API_KEY
)

# =========================================
# WHISPER
# =========================================

model = None

model_lock = threading.Lock()


def obter_modelo_whisper():

    global model

    if model is None:

        with model_lock:

            if model is None:

                print("Carregando Whisper...")

                model = WhisperModel(

                    "base",

                    device="cpu",

                    compute_type="int8"
                )

                print("Whisper carregado!")

    return model

# =========================================
# POSTGRES
# =========================================

def conectar_banco():

    if not DATABASE_URL:

        raise RuntimeError(
            "DATABASE_URL nao configurada"
        )

    return psycopg2.connect(
        DATABASE_URL
    )


def inicializar_banco():

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(

                """

                CREATE TABLE IF NOT EXISTS usuarios (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario TEXT UNIQUE NOT NULL,
                    senha TEXT NOT NULL,
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                )

                """
            )

            cursor.execute(

                """

                CREATE TABLE IF NOT EXISTS atendimentos (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
                    arquivo TEXT,
                    conteudo TEXT,
                    data TEXT
                )

                """
            )

            cursor.execute(

                """

                INSERT INTO usuarios (usuario, senha)
                VALUES (%s, %s)
                ON CONFLICT (usuario) DO NOTHING

                """,

                (
                    ADMIN_USUARIO,
                    ADMIN_SENHA
                )
            )


try:

    inicializar_banco()

except Exception as e:

    print("ERRO AO INICIALIZAR BANCO:", e)

# =========================================
# FILA
# =========================================

processando = []

# =========================================
# LIMPAR TEXTO
# =========================================

def limpar_texto(texto):

    texto = re.sub(
        r'\s+',
        ' ',
        texto
    )

    return texto.strip()

# =========================================
# REMOVER SILENCIO
# =========================================

def remover_silencio(caminho_audio):

    audio = AudioSegment.from_file(
        caminho_audio
    )

    audio = audio.set_channels(1)

    audio = audio.set_frame_rate(16000)

    chunks = split_on_silence(

        audio,

        min_silence_len=800,

        silence_thresh=audio.dBFS - 16,

        keep_silence=250
    )

    if not chunks:

        return caminho_audio

    audio_final = AudioSegment.empty()

    for chunk in chunks:

        audio_final += chunk

    novo_arquivo = caminho_audio.replace(
        ".webm",
        "_limpo.wav"
    )

    audio_final.export(

        novo_arquivo,

        format="wav"
    )

    return novo_arquivo

# =========================================
# TRANSCRICAO
# =========================================

def transcrever_audio(caminho):

    caminho_limpo = remover_silencio(
        caminho
    )

    whisper = obter_modelo_whisper()

    segments, info = whisper.transcribe(

        caminho_limpo,

        language="pt",

        vad_filter=True,

        beam_size=5,

        condition_on_previous_text=False
    )

    texto = ""

    for segment in segments:

        texto += (
            segment.text + " "
        )

    texto = limpar_texto(texto)

    try:

        if os.path.exists(caminho):
            os.remove(caminho)

        if os.path.exists(caminho_limpo):
            os.remove(caminho_limpo)

    except:
        pass

    return texto

# =========================================
# IA
# =========================================

def analisar_com_ia(transcricao):

    prompt = f"""

Você é um analista ERP.

Extraia:

- Empresa
- Cliente
- Telefone
- Email
- Problema
- Resumo curto
- Tags

Máximo 3 linhas.

LIGAÇÃO:
{transcricao}

"""

    resposta = client.chat.completions.create(

        model="gpt-4.1-mini",

        messages=[

            {
                "role": "user",
                "content": prompt
            }

        ]

    )

    return resposta.choices[0].message.content

# =========================================
# LOGIN
# =========================================

@app.route(
    "/login",
    methods=["GET", "POST"]
)

def login():

    if request.method == "POST":

        usuario = request.form["usuario"]

        senha = request.form["senha"]

        with conectar_banco() as conn:

            with conn.cursor() as cursor:

                cursor.execute(

                    """

                    SELECT id
                    FROM usuarios

                    WHERE
                        usuario = %s
                        AND senha = %s

                    """,

                    (
                        usuario,
                        senha
                    )
                )

                user = cursor.fetchone()

        if user:

            session["usuario_id"] = user[0]

            return redirect("/")

    return render_template(
        "login.html"
    )

# =========================================
# LOGOUT
# =========================================

@app.route("/logout")

def logout():

    session.clear()

    return redirect("/login")

# =========================================
# HOME
# =========================================

@app.route("/")

def home():

    if "usuario_id" not in session:

        return redirect("/login")

    return render_template(
        "index.html"
    )

# =========================================
# HEALTH
# =========================================

@app.route("/health")

def health():

    try:

        with conectar_banco() as conn:

            with conn.cursor() as cursor:

                cursor.execute("SELECT 1")

        return jsonify({
            "status": "ok",
            "database": "ok"
        })

    except Exception as e:

        return jsonify({
            "status": "erro",
            "database": str(e)
        }), 500

# =========================================
# PROCESSAR
# =========================================

def processar_em_background(
    caminho_audio,
    nome_arquivo,
    usuario_id
):

    try:

        texto = transcrever_audio(
            caminho_audio
        )

        resultado = analisar_com_ia(
            texto
        )

        data = datetime.now().strftime(
            "%d/%m/%Y %H:%M"
        )

        with conectar_banco() as conn:

            with conn.cursor() as cursor:

                cursor.execute(

                    """

                    INSERT INTO atendimentos (

                        usuario_id,
                        arquivo,
                        conteudo,
                        data

                    )

                    VALUES (%s, %s, %s, %s)

                    """,

                    (
                        usuario_id,
                        nome_arquivo,
                        resultado,
                        data
                    )
                )

    except Exception as e:

        print("ERRO:", e)

    finally:

        if nome_arquivo in processando:

            processando.remove(
                nome_arquivo
            )

# =========================================
# TRANSCRICAO
# =========================================

@app.route(
    "/transcrever",
    methods=["POST"]
)

def transcrever():

    if "usuario_id" not in session:

        return jsonify({
            "erro": "Nao autenticado"
        })

    if "audio" not in request.files:

        return jsonify({
            "erro": "Sem audio"
        })

    arquivo = request.files["audio"]

    nome_arquivo = (
        str(uuid.uuid4()) +
        ".webm"
    )

    caminho_audio = os.path.join(

        UPLOAD_FOLDER,
        nome_arquivo
    )

    arquivo.save(
        caminho_audio
    )

    processando.append(
        nome_arquivo
    )

    thread = threading.Thread(

        target=processar_em_background,

        args=(

            caminho_audio,
            nome_arquivo,
            session["usuario_id"]
        )
    )

    thread.start()

    return jsonify({

        "status": "processando"

    })

# =========================================
# RESULTADOS
# =========================================

@app.route("/resultados")

def resultados():

    if "usuario_id" not in session:

        return jsonify([])

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(

                """

                SELECT
                    id,
                    arquivo,
                    conteudo,
                    data

                FROM atendimentos

                WHERE
                    usuario_id = %s

                ORDER BY id DESC

                LIMIT 100

                """,

                (
                    session["usuario_id"],
                )
            )

            rows = cursor.fetchall()

    resultados = []

    for row in rows:

        resultados.append({

            "id": row[0],

            "arquivo": row[1],

            "conteudo": row[2],

            "data": row[3]
        })

    return jsonify({

        "resultados": resultados,

        "processando": processando

    })

# =========================================
# EXPORTAR
# =========================================

@app.route("/exportar")

def exportar():

    if "usuario_id" not in session:

        return redirect("/login")

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(

                """

                SELECT
                    conteudo,
                    data

                FROM atendimentos

                WHERE
                    usuario_id = %s

                ORDER BY id DESC

                """,

                (
                    session["usuario_id"],
                )
            )

            rows = cursor.fetchall()

    wb = Workbook()

    ws = wb.active

    ws.append([

        "Conteudo",
        "Data"
    ])

    for row in rows:

        ws.append(row)

    nome = "atendimentos.xlsx"

    wb.save(nome)

    return send_file(

        nome,

        as_attachment=True
    )

# =========================================
# START
# =========================================

if __name__ == "__main__":

    serve(

        app,

        host="0.0.0.0",

        port=int(
            os.getenv(
                "PORT",
                "8080"
            )
        ),

        threads=8
    )
