from flask import (
    Flask,
    request,
    jsonify,
    render_template,
    redirect,
    session,
    send_file
)

from flask_cors import CORS
from openai import OpenAI
from waitress import serve
from dotenv import load_dotenv
from datetime import datetime
from openpyxl import Workbook

import psycopg2
import os
import re
import uuid


# =========================================
# ENV
# =========================================

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
DB_HOST = os.getenv(
    "DB_HOST",
    "aws-1-sa-east-1.pooler.supabase.com"
)
DB_PORT = os.getenv("DB_PORT", "6543")
DB_NAME = os.getenv("DB_NAME", "postgres")
DB_USER = os.getenv(
    "DB_USER",
    "postgres.epegojdxngrcwvzecupl"
)
DB_PASSWORD = os.getenv("DB_PASSWORD")

ADMIN_USUARIO = os.getenv("ADMIN_USUARIO", "admin")
ADMIN_SENHA = os.getenv("ADMIN_SENHA", "123456")

TRANSCRIBE_MODEL = os.getenv(
    "TRANSCRIBE_MODEL",
    "gpt-4o-mini-transcribe"
)

SUMMARY_MODEL = os.getenv(
    "SUMMARY_MODEL",
    "gpt-4.1-mini"
)


# =========================================
# FLASK
# =========================================

app = Flask(__name__)

app.secret_key = os.getenv(
    "SECRET_KEY",
    "55pbx_ai"
)

CORS(app)


# =========================================
# OPENAI
# =========================================

client = OpenAI(
    api_key=OPENAI_API_KEY
)


# =========================================
# POSTGRES
# =========================================

def conectar_banco():

    db_password = DB_PASSWORD

    if (
        not db_password
        and DATABASE_URL
        and "postgres:@" in DATABASE_URL
        and "@db." in DATABASE_URL
    ):

        db_password = DATABASE_URL.split(
            "postgres:@",
            1
        )[1].split(
            "@db.",
            1
        )[0]

    if db_password:

        return psycopg2.connect(
            host=DB_HOST,
            port=DB_PORT,
            dbname=DB_NAME,
            user=DB_USER,
            password=db_password,
            sslmode="require"
        )

    if not DATABASE_URL:

        raise RuntimeError(
            "DATABASE_URL ou DB_PASSWORD nao configurada"
        )

    return psycopg2.connect(
        DATABASE_URL
    )


def diagnostico_banco():

    db_password = DB_PASSWORD

    if (
        not db_password
        and DATABASE_URL
        and "postgres:@" in DATABASE_URL
        and "@db." in DATABASE_URL
    ):

        db_password = DATABASE_URL.split(
            "postgres:@",
            1
        )[1].split(
            "@db.",
            1
        )[0]

    if db_password:

        return {
            "modo": "variaveis_db",
            "host": DB_HOST,
            "port": DB_PORT,
            "user": DB_USER,
            "password_configurada": True
        }

    return {
        "modo": "database_url",
        "host": "DATABASE_URL",
        "port": "DATABASE_URL",
        "user": "DATABASE_URL",
        "password_configurada": False
    }


def inicializar_banco():

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS usuarios (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario TEXT UNIQUE NOT NULL,
                    senha TEXT NOT NULL,
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS atendimentos (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
                    arquivo TEXT,
                    conteudo TEXT,
                    data TEXT
                )
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'finalizado'
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ALTER COLUMN data TYPE TEXT
                USING data::TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS transcricao_completa TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS inicio_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS fim_em TIMESTAMP WITH TIME ZONE
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS duracao_segundos INTEGER
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS transcricoes_chunks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    atendimento_id BIGINT REFERENCES atendimentos(id) ON DELETE CASCADE,
                    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
                    ordem INTEGER NOT NULL,
                    texto TEXT,
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                )
                """
            )

            cursor.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS idx_chunks_atendimento_ordem
                ON transcricoes_chunks (atendimento_id, ordem)
                """
            )

            cursor.execute(
                """
                INSERT INTO usuarios (usuario, senha)
                VALUES (%s, %s)
                ON CONFLICT (usuario) DO NOTHING
                """,
                (
                    ADMIN_USUARIO,
                    ADMIN_SENHA
                )
            )


try:

    inicializar_banco()

except Exception as e:

    print("ERRO AO INICIALIZAR BANCO:", e)


# =========================================
# HELPERS
# =========================================

def limpar_texto(texto):

    texto = re.sub(
        r"\s+",
        " ",
        texto or ""
    )

    return texto.strip()


def usuario_logado():

    return session.get("usuario_id")


def transcrever_chunk(arquivo):

    nome = arquivo.filename or "chunk.webm"
    mime = arquivo.mimetype or "audio/webm"

    resposta = client.audio.transcriptions.create(
        model=TRANSCRIBE_MODEL,
        file=(
            nome,
            arquivo.stream,
            mime
        ),
        language="pt",
        prompt=(
            "Atendimento de suporte ERP em portugues do Brasil. "
            "Priorize termos de ERP, fiscal, nota fiscal, caixa, venda, "
            "cadastro, produto, cliente, financeiro, estoque, PDV, NFC-e, "
            "NF-e, SAT, boleto, XML e Zendesk."
        )
    )

    return limpar_texto(
        getattr(resposta, "text", "")
    )


def analisar_com_ia(transcricao):

    prompt = f"""
Voce e um analista de suporte ERP.

Gere uma documentacao curta, direta e pronta para colar no Zendesk.

Regras:
- Nao invente dados.
- Se nao encontrar uma informacao, escreva "Nao informado".
- Mantenha linguagem profissional.
- Extraia tags curtas no final.

Formato:
Empresa:
Cliente:
Telefone:
Email:
Problema:
Resumo do atendimento:
Acao realizada/orientacao:
Tags:

Transcricao:
{transcricao}
"""

    resposta = client.chat.completions.create(
        model=SUMMARY_MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return resposta.choices[0].message.content


# =========================================
# LOGIN
# =========================================

@app.route(
    "/login",
    methods=["GET", "POST"]
)
def login():

    if request.method == "POST":

        usuario = request.form["usuario"]
        senha = request.form["senha"]

        with conectar_banco() as conn:

            with conn.cursor() as cursor:

                cursor.execute(
                    """
                    SELECT id
                    FROM usuarios
                    WHERE usuario = %s
                    AND senha = %s
                    """,
                    (
                        usuario,
                        senha
                    )
                )

                user = cursor.fetchone()

        if user:

            session["usuario_id"] = user[0]

            return redirect("/")

    return render_template(
        "login.html"
    )


@app.route("/logout")
def logout():

    session.clear()

    return redirect("/login")


@app.route("/")
def home():

    if not usuario_logado():

        return redirect("/login")

    return render_template(
        "index.html"
    )


# =========================================
# HEALTH
# =========================================

@app.route("/health")
def health():

    try:

        with conectar_banco() as conn:

            with conn.cursor() as cursor:

                cursor.execute("SELECT 1")

        return jsonify({
            "status": "ok",
            "database": "ok",
            "db_config": diagnostico_banco(),
            "transcribe_model": TRANSCRIBE_MODEL
        })

    except Exception as e:

        return jsonify({
            "status": "erro",
            "database": str(e),
            "db_config": diagnostico_banco()
        }), 500


# =========================================
# ATENDIMENTOS EM CHUNKS
# =========================================

@app.route(
    "/atendimentos/iniciar",
    methods=["POST"]
)
def iniciar_atendimento():

    usuario_id = usuario_logado()

    if not usuario_id:

        return jsonify({
            "erro": "Nao autenticado"
        }), 401

    data = datetime.now().strftime(
        "%d/%m/%Y %H:%M"
    )

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(
                """
                INSERT INTO atendimentos (
                    usuario_id,
                    arquivo,
                    conteudo,
                    data,
                    status,
                    inicio_em
                )
                VALUES (%s, %s, %s, %s, %s, NOW())
                RETURNING id
                """,
                (
                    usuario_id,
                    "streaming",
                    "Transcricao em andamento...",
                    data,
                    "gravando"
                )
            )

            atendimento_id = cursor.fetchone()[0]

    return jsonify({
        "atendimento_id": atendimento_id,
        "status": "gravando"
    })


@app.route(
    "/atendimentos/chunk",
    methods=["POST"]
)
def receber_chunk():

    usuario_id = usuario_logado()

    if not usuario_id:

        return jsonify({
            "erro": "Nao autenticado"
        }), 401

    if "audio" not in request.files:

        return jsonify({
            "erro": "Sem audio"
        }), 400

    atendimento_id = request.form.get("atendimento_id")
    ordem = request.form.get("ordem")

    if not atendimento_id or ordem is None:

        return jsonify({
            "erro": "Atendimento ou ordem ausente"
        }), 400

    arquivo = request.files["audio"]
    texto = transcrever_chunk(arquivo)

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(
                """
                INSERT INTO transcricoes_chunks (
                    atendimento_id,
                    usuario_id,
                    ordem,
                    texto
                )
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (atendimento_id, ordem)
                DO UPDATE SET texto = EXCLUDED.texto
                """,
                (
                    atendimento_id,
                    usuario_id,
                    int(ordem),
                    texto
                )
            )

            cursor.execute(
                """
                UPDATE atendimentos
                SET status = 'transcrevendo'
                WHERE id = %s
                AND usuario_id = %s
                """,
                (
                    atendimento_id,
                    usuario_id
                )
            )

    return jsonify({
        "status": "chunk_transcrito",
        "texto": texto
    })


@app.route(
    "/atendimentos/finalizar",
    methods=["POST"]
)
def finalizar_atendimento():

    usuario_id = usuario_logado()

    if not usuario_id:

        return jsonify({
            "erro": "Nao autenticado"
        }), 401

    dados = request.get_json(silent=True) or {}

    atendimento_id = dados.get("atendimento_id")
    duracao_segundos = dados.get("duracao_segundos")

    if not atendimento_id:

        return jsonify({
            "erro": "Atendimento ausente"
        }), 400

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(
                """
                SELECT texto
                FROM transcricoes_chunks
                WHERE atendimento_id = %s
                AND usuario_id = %s
                ORDER BY ordem
                """,
                (
                    atendimento_id,
                    usuario_id
                )
            )

            textos = [
                row[0]
                for row in cursor.fetchall()
                if row[0]
            ]

    transcricao = limpar_texto(
        " ".join(textos)
    )

    if transcricao:

        resultado = analisar_com_ia(
            transcricao
        )

    else:

        resultado = (
            "Nao foi possivel gerar resumo: "
            "nenhuma transcricao foi capturada."
        )

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(
                """
                UPDATE atendimentos
                SET
                    conteudo = %s,
                    transcricao_completa = %s,
                    status = 'finalizado',
                    fim_em = NOW(),
                    duracao_segundos = %s
                WHERE id = %s
                AND usuario_id = %s
                """,
                (
                    resultado,
                    transcricao,
                    duracao_segundos,
                    atendimento_id,
                    usuario_id
                )
            )

    return jsonify({
        "status": "finalizado",
        "resultado": resultado
    })


# =========================================
# ROTA ANTIGA - COMPATIBILIDADE
# =========================================

@app.route(
    "/transcrever",
    methods=["POST"]
)
def transcrever_arquivo_unico():

    usuario_id = usuario_logado()

    if not usuario_id:

        return jsonify({
            "erro": "Nao autenticado"
        }), 401

    if "audio" not in request.files:

        return jsonify({
            "erro": "Sem audio"
        }), 400

    data = datetime.now().strftime(
        "%d/%m/%Y %H:%M"
    )

    arquivo = request.files["audio"]
    texto = transcrever_chunk(arquivo)
    resultado = analisar_com_ia(texto)

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(
                """
                INSERT INTO atendimentos (
                    usuario_id,
                    arquivo,
                    conteudo,
                    data,
                    status,
                    transcricao_completa,
                    fim_em
                )
                VALUES (%s, %s, %s, %s, %s, %s, NOW())
                """,
                (
                    usuario_id,
                    str(uuid.uuid4()) + ".webm",
                    resultado,
                    data,
                    "finalizado",
                    texto
                )
            )

    return jsonify({
        "status": "finalizado",
        "resultado": resultado
    })


# =========================================
# RESULTADOS
# =========================================

@app.route("/resultados")
def resultados():

    usuario_id = usuario_logado()

    if not usuario_id:

        return jsonify({
            "resultados": [],
            "processando": []
        })

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(
                """
                SELECT
                    id,
                    arquivo,
                    conteudo,
                    data,
                    status
                FROM atendimentos
                WHERE usuario_id = %s
                ORDER BY id DESC
                LIMIT 100
                """,
                (
                    usuario_id,
                )
            )

            rows = cursor.fetchall()

    itens = []
    processando = []

    for row in rows:

        item = {
            "id": row[0],
            "arquivo": row[1],
            "conteudo": row[2],
            "data": row[3],
            "status": row[4]
        }

        itens.append(item)

        if row[4] != "finalizado":

            processando.append(str(row[0]))

    return jsonify({
        "resultados": itens,
        "processando": processando
    })


# =========================================
# EXPORTAR
# =========================================

@app.route("/exportar")
def exportar():

    usuario_id = usuario_logado()

    if not usuario_id:

        return redirect("/login")

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(
                """
                SELECT
                    data,
                    conteudo,
                    transcricao_completa
                FROM atendimentos
                WHERE usuario_id = %s
                ORDER BY id DESC
                """,
                (
                    usuario_id,
                )
            )

            rows = cursor.fetchall()

    wb = Workbook()
    ws = wb.active

    ws.append([
        "Data",
        "Resumo",
        "Transcricao"
    ])

    for row in rows:

        ws.append(row)

    nome = "atendimentos.xlsx"
    wb.save(nome)

    return send_file(
        nome,
        as_attachment=True
    )


# =========================================
# START
# =========================================

if __name__ == "__main__":

    serve(
        app,
        host="0.0.0.0",
        port=int(
            os.getenv(
                "PORT",
                "8080"
            )
        ),
        threads=16
    )
