from contextlib import contextmanager
from threading import BoundedSemaphore, Lock
import atexit

from werkzeug.security import generate_password_hash

import psycopg2
from psycopg2.pool import ThreadedConnectionPool

from config import (
    ADMIN_SENHA,
    ADMIN_USUARIO,
    DATABASE_URL,
    DB_HOST,
    DB_NAME,
    DB_PASSWORD,
    DB_POOL_MAX,
    DB_POOL_MIN,
    DB_PORT,
    DB_USER
)


def senha_banco():

    if (
        not DB_PASSWORD
        and DATABASE_URL
        and "postgres:@" in DATABASE_URL
        and "@db." in DATABASE_URL
    ):

        return DATABASE_URL.split("postgres:@", 1)[1].split("@db.", 1)[0]

    return DB_PASSWORD


_pool = None
_pool_lock = Lock()
_pool_slots = BoundedSemaphore(max(1, DB_POOL_MIN, DB_POOL_MAX))


def parametros_banco():

    db_password = senha_banco()

    if db_password:

        if not all([DB_HOST, DB_PORT, DB_NAME, DB_USER]):

            raise RuntimeError(
                "DB_HOST, DB_PORT, DB_NAME e DB_USER precisam estar configuradas"
            )

        return {
            "host": DB_HOST,
            "port": DB_PORT,
            "dbname": DB_NAME,
            "user": DB_USER,
            "password": db_password,
            "sslmode": "require",
            "connect_timeout": 10
        }

    if not DATABASE_URL:

        raise RuntimeError("DATABASE_URL ou DB_PASSWORD nao configurada")

    return {
        "dsn": DATABASE_URL,
        "connect_timeout": 10
    }


def obter_pool():

    global _pool

    if _pool is not None:

        return _pool

    with _pool_lock:

        if _pool is None:

            parametros = parametros_banco()
            dsn = parametros.pop("dsn", None)

            if dsn:

                _pool = ThreadedConnectionPool(
                    max(1, DB_POOL_MIN),
                    max(1, DB_POOL_MIN, DB_POOL_MAX),
                    dsn,
                    **parametros
                )

            else:

                _pool = ThreadedConnectionPool(
                    max(1, DB_POOL_MIN),
                    max(DB_POOL_MIN, DB_POOL_MAX),
                    **parametros
                )

    return _pool


@contextmanager
def conectar_banco():

    _pool_slots.acquire()
    conn = None
    pool = None

    try:

        pool = obter_pool()
        conn = pool.getconn()

        if conn.closed:

            pool.putconn(conn, close=True)
            conn = pool.getconn()

        yield conn
        conn.commit()

    except Exception as exc:

        descartar = isinstance(
            exc,
            psycopg2.OperationalError
        )

        if conn and not conn.closed:

            try:

                conn.rollback()

            except Exception:

                descartar = True

        if conn and pool:

            pool.putconn(
                conn,
                close=(
                    descartar
                    or bool(conn.closed)
                )
            )
            conn = None

        raise

    finally:

        if conn and pool:

            pool.putconn(
                conn,
                close=bool(conn.closed)
            )

        _pool_slots.release()


def fechar_pool():

    global _pool

    with _pool_lock:

        if _pool is not None:

            _pool.closeall()
            _pool = None


atexit.register(fechar_pool)


def diagnostico_banco():

    db_password = senha_banco()

    if db_password:

        return {
            "modo": "variaveis_db",
            "host": DB_HOST,
            "port": DB_PORT,
            "user": DB_USER,
            "password_configurada": True
        }

    return {
        "modo": "database_url",
        "host": "DATABASE_URL",
        "port": "DATABASE_URL",
        "user": "DATABASE_URL",
        "password_configurada": False
    }


def inicializar_banco():

    with conectar_banco() as conn:

        with conn.cursor() as cursor:

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS usuarios (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario TEXT UNIQUE NOT NULL,
                    senha TEXT NOT NULL,
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                )
                """
            )

            cursor.execute(
                """
                ALTER TABLE usuarios
                ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE
                """
            )

            cursor.execute(
                """
                ALTER TABLE usuarios
                ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT TRUE
                """
            )

            cursor.execute(
                """
                ALTER TABLE usuarios
                ADD COLUMN IF NOT EXISTS perfil TEXT DEFAULT 'analista'
                """
            )

            cursor.execute(
                """
                UPDATE usuarios
                SET perfil = 'admin_tecnico'
                WHERE is_admin = TRUE
                AND (
                    perfil IS NULL
                    OR perfil = 'analista'
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS atendimentos (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
                    arquivo TEXT,
                    conteudo TEXT,
                    data TEXT
                )
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'finalizado'
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ALTER COLUMN data TYPE TEXT
                USING data::TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS transcricao_completa TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS inicio_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS fim_em TIMESTAMP WITH TIME ZONE
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS duracao_segundos INTEGER
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS chunks_total INTEGER DEFAULT 0
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS chunks_falhos INTEGER DEFAULT 0
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS chunks_ignorados INTEGER DEFAULT 0
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS segundos_transcritos INTEGER DEFAULT 0
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS custo_estimado_usd NUMERIC(10, 4) DEFAULT 0
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS ticket_zendesk TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS resumo_editado BOOLEAN DEFAULT FALSE
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS resumo_editado_em TIMESTAMP WITH TIME ZONE
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS sentimento_cliente TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS urgencia TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS categoria TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS problema_principal TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS tags TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE atendimentos
                ADD COLUMN IF NOT EXISTS finalizacao_iniciada_em TIMESTAMP WITH TIME ZONE
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS transcricoes_chunks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    atendimento_id BIGINT REFERENCES atendimentos(id) ON DELETE CASCADE,
                    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
                    ordem INTEGER NOT NULL,
                    texto TEXT,
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                )
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'transcrito'
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS erro TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS provider_tentado TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS provider_usado TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS fallback_usado BOOLEAN DEFAULT FALSE
                """
            )
            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS motivo_fallback TEXT
                """
            )


            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS duracao_segundos INTEGER
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS transcricao_bruta TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS transcricao_normalizada TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS transcricao_limpa_para_resumo TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS modelo_usado TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS tamanho_audio_original INTEGER
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS tamanho_audio_processado INTEGER
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS audio_processado BOOLEAN DEFAULT FALSE
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS audio_original_path TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS audio_processado_path TEXT
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS tempo_transcricao_segundos NUMERIC(10, 4)
                """
            )

            cursor.execute(
                """
                ALTER TABLE transcricoes_chunks
                ADD COLUMN IF NOT EXISTS erro_preprocessamento TEXT
                """
            )

            cursor.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS idx_chunks_atendimento_ordem
                ON transcricoes_chunks (atendimento_id, ordem)
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS login_tentativas (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario TEXT NOT NULL,
                    ip TEXT NOT NULL,
                    tentativas INTEGER DEFAULT 0,
                    bloqueado_ate TIMESTAMP WITH TIME ZONE,
                    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                    UNIQUE (usuario, ip)
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS uso_eventos (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
                    atendimento_id BIGINT REFERENCES atendimentos(id) ON DELETE SET NULL,
                    tipo TEXT NOT NULL,
                    custo_usd NUMERIC(10, 4) DEFAULT 0,
                    custo_brl NUMERIC(10, 4) DEFAULT 0,
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                )
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_uso_eventos_dia_usuario
                ON uso_eventos (usuario_id, criado_em)
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS auditoria_eventos (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ator_usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
                    acao TEXT NOT NULL,
                    alvo_tipo TEXT NOT NULL,
                    alvo_id BIGINT,
                    detalhes TEXT,
                    ip TEXT,
                    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                )
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_auditoria_criado
                ON auditoria_eventos (criado_em DESC)
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_auditoria_ator_criado
                ON auditoria_eventos (ator_usuario_id, criado_em DESC)
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_atendimentos_usuario_id_desc
                ON atendimentos (usuario_id, id DESC)
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_atendimentos_usuario_inicio
                ON atendimentos (usuario_id, inicio_em DESC)
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_atendimentos_status_inicio
                ON atendimentos (status, inicio_em DESC)
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_chunks_usuario_criado
                ON transcricoes_chunks (usuario_id, criado_em DESC)
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_usuarios_ativo_usuario
                ON usuarios (ativo, usuario)
                """
            )

            admin_hash = generate_password_hash(ADMIN_SENHA)

            cursor.execute(
                """
                INSERT INTO usuarios (usuario, senha, is_admin, ativo)
                VALUES (%s, %s, TRUE, TRUE)
                ON CONFLICT (usuario) DO NOTHING
                """,
                (
                    ADMIN_USUARIO,
                    admin_hash
                )
            )

            cursor.execute(
                """
                UPDATE usuarios
                SET is_admin = TRUE,
                    ativo = TRUE,
                    perfil = 'admin_tecnico'
                WHERE usuario = %s
                """,
                (
                    ADMIN_USUARIO,
                )
            )
